src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email(
        message: 'The email {{ value }} is not a valid email.',
    )]
    private ?string $email = null;

    #[ORM\Column(type: 'simple_array')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotCompromisedPassword]
    #[Assert\Length(
        min: 8,
        max: 4096,
        minMessage: 'Your password must be at least {{ limit }} characters long',
        maxMessage: 'Your password cannot be longer than {{ limit }} characters',
    )]
    #[Assert\Regex(
        pattern: '/^.*(?=.{8,})(?=.*[a-zA-Z])(?=.*\d)(?=.*[!#$%&? "]).*$/',
        message: 'Your password must contain letters, numbers, special characters, and be at least 8 characters long.'
    )]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Pseudo = null;

    #[ORM\OneToMany(mappedBy: 'collector', targetEntity: UserPicture::class)]
    /**
     * @var Collection<int, UserPicture>
     */
    private Collection $userPictures;

    public function __construct()
    {
        $this->userPictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @return $this
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(?string $Pseudo): static
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    /**
     * @return Collection<int, UserPicture>
     */
    public function getUserPictures(): Collection
    {
        return $this->userPictures;
    }

    public function addUserPicture(UserPicture $userPicture): static
    {
        if (!$this->userPictures->contains($userPicture)) {
            $this->userPictures->add($userPicture);
            $userPicture->setCollector($this);
        }

        return $this;
    }

    public function removeUserPicture(UserPicture $userPicture): static
    {
        if ($this->userPictures->removeElement($userPicture)) {
            // set the owning side to null (unless already changed)
            if ($userPicture->getCollector() === $this) {
                $userPicture->setCollector(null);
            }
        }

        return $this;
    }
}

templates/_footer.html.twig
{#    footer#}
<footer class="bg-gradient-to-l from-sky-950 to-sky-100 mt-auto">
    <div class="container max-w-6xl mx-auto flex items-center px-2 py-8">

        <div class="w-full mx-auto flex flex-wrap items-center">
            <div class="flex w-full md:w-1/2 justify-center md:justify-start text-white font-extrabold">
                <p class="text-gray-900 no-underline hover:text-gray-900 hover:no-underline">
                    👻 <span class="text-base text-black">Thibaut Taglialatela</span>
                </p>
            </div>
        </div>
    </div>
</footer>
<!--Footer container-->

templates/_navbar.html.twig
<!-- Main navigation container -->
<nav
        class="sticky top-0 flex-no-wrap flex w-full items-center justify-between bg-gradient-to-r from-sky-950 to-sky-100 py-2 shadow-md shadow-black/5 dark:bg-neutral-600 dark:shadow-black/10 lg:flex-wrap lg:justify-start lg:py-4">
    <div class="flex w-full flex-wrap items-center justify-between px-3">
        <!-- Hamburger button for mobile view -->
        <button
                class="block border-0 bg-transparent px-2 text-neutral-500 hover:no-underline hover:shadow-none focus:no-underline focus:shadow-none focus:outline-none focus:ring-0 dark:text-neutral-200 lg:hidden"
                type="button"
                data-te-collapse-init
                data-te-target="#navbarSupportedContent1"
                aria-controls="navbarSupportedContent1"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <!-- Hamburger icon -->
            <span class="[&>svg]:w-7">
        <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                class="h-7 w-7">
          <path
                  fill-rule="evenodd"
                  d="M3 6.75A.75.75 0 013.75 6h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 6.75zM3 12a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 12zm0 5.25a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75a.75.75 0 01-.75-.75z"
                  clip-rule="evenodd"/>
        </svg>
      </span>
        </button>

        <!-- Collapsible navigation container -->
        <div
                class="!visible hidden flex-grow basis-[100%] items-center lg:!flex lg:basis-auto"
                id="navbarSupportedContent1"
                data-te-collapse-item>
            <!-- Logo -->
            <div
                    class="mb-4 ml-2 mr-5 mt-3 flex items-center text-neutral-900 hover:text-neutral-900 focus:text-neutral-900 dark:text-neutral-200 dark:hover:text-neutral-400 dark:focus:text-neutral-400 lg:mb-0 lg:mt-0"
            >
                <img
                        src="{{ asset('build/logo-rocket-wonders.png') }}"
                        style="height: 2.5rem"
                        alt="TE Logo"
                        loading="lazy"/>
            </div>
            <!-- Left navigation links -->
            {% set currentUrl = app.request.getRequestUri() %}
            <ul
                    class="list-style-none mr-auto flex flex-col pl-0 lg:flex-row"
                    data-te-navbar-nav-ref>
                <li class="mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
                    <!-- HomePage link -->
                    <a
                            class="{{ currentUrl == path('home_index') ? 'text-blue-500' : 'text-neutral-50 transition duration-200 hover:text-neutral-100 hover:ease-in-out' }} hover:underline hover:ease-in-out focus:text-neutral-200 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 lg:px-2"
                            href="{{ path('home_index') }}"
                            data-te-nav-link-ref
                    >Home</a
                    >
                </li>
                <li class="mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
                    <!-- CarouselPage link -->
                    <a
                            class="{{ currentUrl == path('app_carousel') ? 'text-blue-500' : 'text-neutral-50 transition duration-200 hover:text-neutral-100 hover:ease-in-out' }} hover:underline hover:ease-in-out focus:text-neutral-200 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 lg:px-2"
                            href="{{ path('app_carousel') }}"
                            data-te-nav-link-ref
                    >Images from the NASA</a
                    >
                </li>
                <li class="mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
                    <!-- CarouselPage link -->
                    <a
                            class="{{ currentUrl == path('app_picture_index') ? 'text-blue-500' : 'text-neutral-50 transition duration-200 hover:text-neutral-100 hover:ease-in-out' }} hover:underline hover:ease-in-out focus:text-neutral-200 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 lg:px-2"
                            href="{{ path('app_picture_index') }}"
                            data-te-nav-link-ref
                    >Images from our users</a
                    >
                </li>

                {% if app.user %}
                {% else %}
                    <!-- Login link -->
                    <li class="mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
                        <a
                                class="{{ currentUrl == path('app_login') ? 'text-blue-500' : 'text-neutral-50 transition duration-200 hover:text-neutral-100 hover:ease-in-out' }} focus:text-neutral-200 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 lg:px-2 [&.active]:text-black/90 dark:[&.active]:text-neutral-400"
                                href="{{ path('app_login') }}"
                                data-te-nav-link-ref
                        >Login</a
                        >
                    </li>
                {% endif %}
            </ul>
        </div>

        <!-- Right elements -->
        <div class="relative flex items-center">
            {% if app.user %}
                <div class="text-neutral-700 transition duration-200 focus:text-neutral-200 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 lg:px-2 [&.active]:text-black/90 dark:[&.active]:text-neutral-400">
                    {{ app.user.pseudo ? app.user.pseudo : app.user.email }} is connected
                </div>
                <!-- Logout link -->
                <a
                        class="text-neutral-700 transition duration-200 hover:underline hover:ease-in-out focus:text-neutral-200 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 lg:px-2 [&.active]:text-black/90 dark:[&.active]:text-neutral-400"
                        href="{{ path('app_logout') }}"
                        data-te-nav-link-ref
                >Logout</a
                >
            {% endif %}
        </div>
    </div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Wonders from the sky{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body class="bg-sky-950 font-sans leading-normal tracking-normal flex flex-col min-h-screen">
    {% include'_navbar.html.twig' %}
    {% for message in app.flashes('notice') %}
    <div class="bg-green-200 text-green-800 p-4 mb-4">
        {{ message }}
    </div>
    {% endfor %}
        {% block body %}{% endblock %}

    {% include '_footer.html.twig' %}
    </body>
</html>